/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppInterventionsRouteImport } from './routes/app.interventions'
import { Route as AppSegmentsRouteImport } from './routes/app.segments'
import { Route as AppSessionsRouteImport } from './routes/app.sessions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppInterventionsIndexRouteImport } from './routes/app.interventions.index'
import { Route as AppInterventionsBuilderRouteImport } from './routes/app.interventions.builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsRoute = AppInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsRoute = AppSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsIndexRoute = AppInterventionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInterventionsRoute,
} as any)
const AppInterventionsBuilderRoute = AppInterventionsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppInterventionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/interventions': typeof AppInterventionsRouteWithChildren
  '/app/segments': typeof AppSegmentsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/interventions/builder': typeof AppInterventionsBuilderRoute
  '/app/interventions/': typeof AppInterventionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/segments': typeof AppSegmentsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/app/interventions/builder': typeof AppInterventionsBuilderRoute
  '/app/interventions': typeof AppInterventionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/interventions': typeof AppInterventionsRouteWithChildren
  '/app/segments': typeof AppSegmentsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/app/interventions/builder': typeof AppInterventionsBuilderRoute
  '/app/interventions/': typeof AppInterventionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/analytics'
    | '/app/billing'
    | '/app/integrations'
    | '/app/interventions'
    | '/app/segments'
    | '/app/sessions'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/app/interventions/builder'
    | '/app/interventions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/analytics'
    | '/app/billing'
    | '/app/integrations'
    | '/app/segments'
    | '/app/sessions'
    | '/app/settings'
    | '/app/team'
    | '/app'
    | '/app/interventions/builder'
    | '/app/interventions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/analytics'
    | '/app/billing'
    | '/app/integrations'
    | '/app/interventions'
    | '/app/segments'
    | '/app/sessions'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/app/interventions/builder'
    | '/app/interventions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interventions': {
      id: '/app/interventions'
      path: '/interventions'
      fullPath: '/app/interventions'
      preLoaderRoute: typeof AppInterventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/segments': {
      id: '/app/segments'
      path: '/segments'
      fullPath: '/app/segments'
      preLoaderRoute: typeof AppSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interventions/': {
      id: '/app/interventions/'
      path: '/'
      fullPath: '/app/interventions/'
      preLoaderRoute: typeof AppInterventionsIndexRouteImport
      parentRoute: typeof AppInterventionsRoute
    }
    '/app/interventions/builder': {
      id: '/app/interventions/builder'
      path: '/builder'
      fullPath: '/app/interventions/builder'
      preLoaderRoute: typeof AppInterventionsBuilderRouteImport
      parentRoute: typeof AppInterventionsRoute
    }
  }
}

interface AppInterventionsRouteChildren {
  AppInterventionsBuilderRoute: typeof AppInterventionsBuilderRoute
  AppInterventionsIndexRoute: typeof AppInterventionsIndexRoute
}

const AppInterventionsRouteChildren: AppInterventionsRouteChildren = {
  AppInterventionsBuilderRoute: AppInterventionsBuilderRoute,
  AppInterventionsIndexRoute: AppInterventionsIndexRoute,
}

const AppInterventionsRouteWithChildren =
  AppInterventionsRoute._addFileChildren(AppInterventionsRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInterventionsRoute: typeof AppInterventionsRouteWithChildren
  AppSegmentsRoute: typeof AppSegmentsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInterventionsRoute: AppInterventionsRouteWithChildren,
  AppSegmentsRoute: AppSegmentsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
